{% set name = "fabio" %}
{% set version = "2022.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f48899a205e014cb4812a27c982927cb7d563bc40dc1285f2c84cfbb6f4955d3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - meson-python
    - numpy
    - cython
    - tomli

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow
    - lxml
    - glymur

test:
  imports:
    - fabio
    - fabio.test
    - fabio.third_party

about:
  home: https://github.com/silx-kit/fabio
  license: MIT AND LGPL-3.0-or-later
  summary: I/O library for images produced by 2D X-ray detector
  license_family: Other
  license_file: copyright

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - dmpelt
    - CJ-Wright
    - tschoonj
    - vallsv
    - t20100
    - kif
