{% set name = "fabio" %}
{% set version = "0.13.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42d2b04cc602a018bda1a6822725a75148674ab561410a0f99036dd9361c624a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow
    - lxml
    - glymur

test:
  imports:
    - fabio
    - fabio.test
    - fabio.third_party

about:
  home: https://github.com/silx-kit/fabio
  license: MIT AND LGPL-3.0-or-later
  summary: I/O library for images produced by 2D X-ray detector
  license_family: Other
  license_file: copyright

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - dmpelt
    - CJ-Wright
    - tschoonj
    - vallsv
    - t20100
    - kif
