{% set version = "0.7.0" %}

package:
    name: fabio
    version: {{ version }}

source:
    url: https://github.com/silx-kit/fabio/archive/v{{ version }}.tar.gz
    fn: fabio-v{{ version }}.tar.gz
    sha256: f2ba37584fe39e051cff89a61f13615a973e4bdc6f35979011057a1f9305d784

build:
    number: 1001
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - pip
        - setuptools
        - numpy
        - cython
        # could use opencl, but need the package on conda-forge first
        # - opencl

    run:
        - python
        - {{ pin_compatible('numpy') }}

test:
    imports:
        - fabio
        - fabio.test
        - fabio.third_party

about:
    home: https://github.com/silx-kit/fabio
    license: GPL v3.0, GPL v2.0, MIT, GPL, LGPL v3.0, BSD 3-Clause, Apache 2.0
    summary: I/O library for images produced by 2D X-ray detector
    license_family: Other
    license_file: copyright

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - dmpelt
        - CJ-Wright
