{% set name = "fabio" %}
{% set version = "2025.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c19763bcfa02a78a507f3d914b564a8997c88a6aa7b4f87f9db4ce7fa397d256

build:
  number: 0
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - python-build
    - pip
    - meson-python >=0.11
    - meson >=0.64
    - ninja
    - wheel
    - cython >=0.29
    - numpy
    - pyproject-metadata >=0.5.0
    - tomli >=1.0.0
  run:
    - python
    - h5py
    - hdf5plugin
    - lxml
    - pillow
    - glymur

test:
  imports:
    - fabio
    - fabio.test

about:
  home: https://github.com/silx-kit/fabio
  license: MIT AND LGPL-3.0-or-later
  summary: I/O library for images produced by 2D X-ray detector
  license_family: Other
  license_file: copyright

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - dmpelt
    - CJ-Wright
    - tschoonj
    - vallsv
    - t20100
    - kif
