{% set name = "fabio" %}
{% set version = "2023.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c77fcec19e6fd749b95f1033d24f92ee7277a495707da8f23897a9acabcbdc48

build:
  number: 0
  script:
    - {{ PYTHON }} setup.py bdist_wheel
    - {{ PYTHON }} -m pip install --pre --find-links dist/  --no-cache-dir --no-index --no-deps --ignore-installed -vv fabio
#    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - python-build
    - setuptools
    - meson-python
    - ninja
    - meson
    - numpy
    - cython

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow
    - lxml
    - glymur

test:
  imports:
    - fabio
    - fabio.test

about:
  home: https://github.com/silx-kit/fabio
  license: MIT AND LGPL-3.0-or-later
  summary: I/O library for images produced by 2D X-ray detector
  license_family: Other
  license_file: copyright

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - dmpelt
    - CJ-Wright
    - tschoonj
    - vallsv
    - t20100
    - kif
