{% set name = "fabio" %}
{% set version = "2026.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d18193b37c61af83add793c5619dc02d22f3a4e54c448f7bad89f97d0949f4ff

build:
  number: 0
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - python-build
    - pip
    - meson-python >=0.11
    - meson >=0.64
    - ninja
    - wheel
    - cython >=0.29
    - numpy
    - pyproject-metadata >=0.5.0
    - tomli >=1.0.0
    - filelock
  run:
    - python
    - h5py
    - hdf5plugin
    - lxml
    - pillow
    - glymur
    - qtpy

test:
  imports:
    - fabio
    - fabio.test

about:
  home: https://github.com/silx-kit/fabio
  license: MIT AND LGPL-3.0-or-later
  summary: I/O library for images produced by 2D X-ray detector
  license_family: Other
  license_file: copyright

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - dmpelt
    - CJ-Wright
    - tschoonj
    - vallsv
    - t20100
    - kif
