appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: MsP6YWOdwt0WVMlF8sDBqpWvofI7/wxH/RoejTNu0fiWI6Q7M4NBIEAsaMPnQEZlD6xE1gXk2O6CQnHDnHeTCNUmx2SujPw0q7tioE7M2jAKyQluicMtHGMJVZyHk95jlRv1Ql28GFvXSBwRAmhFEYmUapt49YO+F/CFLOYucJ55wH9Fx54aS9ro29QtGXdlcJNkw2up9qlu4TDftzkgBPrJ0nJYnLteZJEsMrtmYX27khME7GtTXU688UQLBJ4giO9BOyLAwEhH+WJqX4uyNrakZYtHjan4eIDMmtBzewy7pjpM2ZQMAnTh4DGt94l0LXzD64d3GKbdZZx1ORLXyx8ZhGzHrIt7IgTzUiWKGfAiOQzlBwr21BHId555RvwCgIs3dxh3WthaIHqtSghx3TX1BR6XSgEDJuOU5hL+ymrp15m13WWFfjkIM6CzGyyd+dEgiZDl5IexKep4ibcSoHUDJ3/gRv12BUynZHl4C+3oCT7QGl8aqAj3TVN5R4m7W1Z0cglCsv3ssJF1StBI/i6Cu7QwIhkviC4N7zxtCr28cipuVYb9rr1sya10MrHCGOfGcL0NWUmH64MT7w6lSrINU5hlN5h48waUGVYR/GAywU8Q09reIPMQzsdD+k+CtYxVGc2njoWGvV47wcQ6XVPuneASgXHeRAv0qtMW7uU=}
provider:
  win: azure
conda_forge_output_validation: true
